### ISSUE TITLE
Sort by Departure Time

### ISSUE THREAD

**Issue by Dominik-AT** [fewieden/MMM-WienerLinien#16]
Platform (Hardware/OS): Raspberry PI 4 / Raspberry PI OS

Node version: 2.6.1

MagicMirror version: 2.13.0

Module version: 2.0.0

Description of the issue:
Somehow the departures on my screen are not sorted by departure, but by line. Is it possible to sort by departure? Reason: different lines go same direction and it doesn't matter which line I take.
I guess this works as designed, right? If not , please let me know if you need any screenshots.

**Comment by fewieden** [comment]
Hi, @Dominik-AT according to this line the departures should be sorted by time not by lines, except they have different station ids.

I think it would be easiest if you can provide the config for this specific module. Please don't forget to remove the API key before posting it here, if you still have it in there from earlier versions of the module.

**Comment by Dominik-AT** [comment]
Hi @fewieden ,
thanks for your reply & thanks for the development of this awesome module! (To be honest: your module was the main reason I even bought a raspberry pi and built the mirror!)

Actually I am only using one single station ids (3 different lines).
Most of the time it only shows two lines and not all 3 of them - but I guess the reason is, it's not sorted by departure.

Please find below my current config for this module. Did I miss anything?
BR, Dominik

```
{
			module: 'MMM-WienerLinien',
			position: 'bottom_left',
			config: {
				stations: ['3348'],
				max: 6,
				rotateInterval: 30000,
				updateInterval: 30000,
				incidentLines: ['99A', '99B', 'U2', '89A'],
				incidentShort: true
			}
		},
```

**Comment by Dominik-AT** [comment]
Update: I tried to "re-install" the whole module, also to reduce the config to the only essential one - but I guess it's a bug. Can't find any issue here. (please correct me if I am wrong)
BR, Dominik

**Comment by fewieden** [comment]
@Dominik-AT I finally had the time to look into it. I used your config to debug the issue. The sorting mechanism that was inside the node_helper never worked. I fixed it now on the develop branch. In order for you to test it follow the following commands:

```bash
cd ~/MagicMirror/modules/MMM-WienerLinien
git checkout develop
git pull
cd ../..
npm start
```

I'm glad that my module introduced you to the MagicMirror world.

**Comment by Dominik-AT** [comment]
seems to be working now! (although after git pull it said "Bereits aktuell")
thanks a lot for your help!
