### ISSUE TITLE
Table will be wider if the content changes

### ISSUE THREAD

**Issue by schlachtkreuzer6** [fewieden/MMM-WienerLinien#2]
If the content, station name or departure time changes, the whole table expanding sideways. So is there a possibility to shorten the content by cropping it?

**Comment by fewieden** [comment]
new config options shortenStation and shortenDestination

**Comment by schlachtkreuzer6** [comment]
Perfect thanks! :)

**Comment by fewieden** [comment]
this output is generated by the moment.js library
